version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    working_directory: ~/repo
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  test:
    working_directory: ~/repo
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
  publish:
    working_directory: ~/repo
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ~/repo
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: npm version $CIRCLE_TAG
      - run: npm publish

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build
      - test
      - publish:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
