version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                registry-url: 'https://registry.npmjs.org'
            - run: yarn   
            - run: yarn publish --new-version $CIRCLE_TAG
              env:
                NODE_AUTH_TOKEN: $NPM_TOKEN

workflows:
    version: 2
    build-and-test:
      jobs:
        - build
        - test
    npm-publish:
      jobs:
        - publish:
            filters:
              branches:
                only: master
              tags:
                only: /.*/
