version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: node/default
    working_directory: ~/repo
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
  test:
    executor:
      name: node/default
    working_directory: ~/repo
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
  publish:
    executor:
      name: node/default
    working_directory: ~/repo  
    steps:
      - attach_workspace:
          at: ~/repo
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: npm version $CIRCLE_TAG
      - run: npm publish

workflows:
    version: 2
    build-test-publish:
      jobs:
        - build
        - test
        - publish:
            requires:
              - build
              - test
            filters:
              branches:
                only: master
              tags:
                only: /^\d+\.\d+\.\d+/
